### ISSUE TITLE
Cant change the device

### ISSUE THREAD

**Issue by KaiserRGB** [iobroker-community-adapters/ioBroker.mihome-vacuum#147]
I cant save my chosen device. It always jumps back to the highst device in my dvice-list if i save the settings.

**Comment by dirkhe** [comment]
which Version do you have installed?

**Comment by KaiserRGB** [comment]
The adapterversion is version 2.0.7
My Node.js is v10.20.1 on an Raspberry Pi.

**Comment by dirkhe** [comment]
I am not shure, but test current Version, it could be, that was already fixed..

**Comment by dirkhe** [comment]
No, you have to install fron github.

**Comment by KaiserRGB** [comment]
Now I have updated the adapter to version 2.0.9 and my Node.js to version v10.21.0.
The problem is still the same. The device selection always jumps back to the highest device in the list when saving.

**Comment by mc-gl89** [comment]
Ive got the same Problem

**Comment by dirkhe** [comment]
Did you mean the Device vor choosing the key? This is not saved, because you choose your Device to get the Token and the Token will be saved

**Comment by KaiserRGB** [comment]
Oh okay. Then that was my mistake. The adapter saves the token and the IP parameters.
Then somewhere else I have a mistake that a connection with mihome-vaccum can no longer be established.

**Comment by KaiserRGB** [comment]
@dirkhe 
Thanks for your help and support.
